apiVersion: v1
kind: Namespace
metadata:
  name: bonsai
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bonsai-quota
  namespace: bonsai
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.storage: 10Gi
    persistentvolumeclaims: "3"
    services.loadbalancers: "2"
    services.nodeports: "2" 