apiVersion: v1
kind: Secret
metadata:
  name: bonsai-secrets
  namespace: bonsai
type: Opaque
data:
  DATABASE_USER: ${BASE64_ENCODED_DB_USER}
  DATABASE_PASSWORD: ${BASE64_ENCODED_DB_PASSWORD}
  SECRET_KEY: ${BASE64_ENCODED_SECRET_KEY}
  AWS_ACCESS_KEY_ID: ${BASE64_ENCODED_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_ENCODED_AWS_SECRET_ACCESS_KEY} 