apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: bonsai-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bonsai-media-pvc
  namespace: bonsai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bonsai-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bonsai-static-pvc
  namespace: bonsai
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bonsai-storage
  resources:
    requests:
      storage: 1Gi 