# Generated by Django 5.1 on 2025-04-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_shippingprice_alter_order_taxprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_type',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='default/placeholder.jpg', null=True, upload_to='products/'),
        ),
    ]
